---
linters:
  LeadingZero:
    enabled: false
  ImportantRule:
    enabled: false
  SelectorFormat:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  ZeroUnit:
    enabled: false
  NestingDepth:
    enabled: false
    max_depth: 5
  SelectorDepth:
    enabled: false
    max_depth: 5
  PropertySortOrder:
    order: concentric
  NameFormat:
    enabled: false
