---
exclude:
  - src/app/styles/_xeditable.scss
  - src/app/styles/_settings.scss
linters:
  LeadingZero:
    enabled: false
  ImportantRule:
    enabled: false
  SelectorFormat:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  ZeroUnit:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  PropertySortOrder:
    order: concentric
    separate_groups: true
  NameFormat:
    enabled: false