define([], function() {
  'use strict';
  return {
      aboutMe: 'About Me',
      addBlacklist: '+',
      addInterest: '+',
      allLikesAreAlreadyAdded: 'Wunderbar! All likes on this page are already added.',
      blacklist: 'Blacklist',
      blacklistEmpty: 'Your blacklist is empty',
      blacklistedExists: 'I already grok you aren\'t interested in receiving messages from them.',
      buttonLabel: {
        sendMessage: 'Send Message',
        name: 'Name',
        message: 'Message',
        messagesListTest: 'Messages List Test',
        ilcServerTest: 'ILC Server Test',
        cardTest: 'Card Test'
      },
      chattingWith: 'with',
      close: '✖️',
      connectedToFacebook: 'Connected To Facebook.',
      count: 'Count',
      contact: 'Contact',
      commonInterests: 'Common Interests',
      currentInterest: 'Current Interest',
      currentInterests: 'Current Interests',
      currentRoom: 'Current Room',
      email: 'Alternate email',
      emptyUserInfo:'No user info, sorry!',
      errors: {
        noName: 'Look bro, I\'m not saying what you have to put in this box, but you have to put something!'
      },
      fallbackLikes: ['Gold mining', 'Oil Wells', 'Shipping', 'Real Estate'],
      facebookHandlesImagesWarning: 'Facebook Handles what images are shown to the users.',

      facebookInterests: 'Facebook Interests',
      facebookInterestsEmpty: 'Facebook likes were empty, sorry!',
      facebookInterestsError: 'Facebook likes failed. Please ensure you\'ve authorized the app to have access to this' +
        ' data (or don\'t use this feature).',
      interestExists: 'I already know you\'re interested in that, silly',
      interests: 'Interests',
      incompleteProfile: 'Please complete your profile before moving on.',
      loading:'loading',
      missing: 'Missing',
      anInterest: 'an interest',
      issues: 'Issues',
      matches: 'Matches',
      messageList: 'Messages List',
      messages: 'Messages',
      messagesFailedToLoad: 'Messages failed to load. Sorry!',
      name: 'Name',
      noCurrentRoom: 'There are no current rooms available to you.  ' +
        'Are you sure you have any one who\'s willing to hear you prattle?',
      noMatches: 'Bottom of the barrel.',
      noRooms: 'No Messages, sorry Bro.',
      profile: 'Profile',
      rooms: 'Rooms',
      send: 'Send',
      sendMessage: 'Send Message',
      siteTitle: '🔥 📖 💬',
      source: 'Source',
      topInterests: 'Top Interests',
      suggestFacebookInterests: 'Suggest Facebook Interests?',
      suggestionsFromFacebook: 'Suggestions from ',
      open: '?',
      updateRoom: 'Update Room',
      updateUser: 'Update User',
      welcomeTo: 'Welcome to',
      whatAreYouInterestedInChattingAbout:'What are you interested in chatting about?'
    };
});
